version: '3.7'
services:
  web:
    build:
      context: MessageHash/app.py
    ports:
     - "8080:8080"
    environment:
     - SCHEME=http
     - IP_ADDRESS=127.0.0.1
     - PORT=8080
  redis:
    image: "redis:alpine"